version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: pub
    directories:
      - '/parts/part-*'
      - '/master-projects/*'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      pub-dependencies:
        patterns:
          - '*'
