name: dfm_quizforge
publish_to: none
description: Quiz engine and assessment master project for Dart & Flutter Full Mastery.
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
